### ISSUE TITLE
Custom containers built on databricksruntime/standard are still missing required packages?

### ISSUE THREAD

**Issue by mattmazzola** [databricks/containers#131]
I am trying to crate Compute cluster which uses a customize container to run my Notebooks

I have followed the steps here: https://learn.microsoft.com/en-us/azure/databricks/clusters/custom-containers#step-1-build-your-base

- Enabled containers for workspace
- Use 13.2 runtime
- Created and push image based on `databricksruntime/standard`

I can create the compute, connect a notebook to it; however, when I try to execute a notebook cell. I would receive an error like this:

> Failure starting repl. Try detaching and re-attaching the notebook.
> ModuleNotFoundError: No module named 'google'

Detaching and Reattaching had no effect.

Then instead of trying to use my custom image, I tried to use `databricksruntime/standard:latest` directly but received a similar error about a different package.

## Expected

I expected if I use `databricksruntime/standard` it would essentially be recreating the default and it should work as if I had not configured the cluster to use a custom container

## Actual

It seems even when using `databricksruntime/standard` there is still more packages or configuration that needs to be made

Is there documentation about these extra configuration or package install steps so that I may use a custom container?

### Full Error

```
java.lang.Exception: Unable to start python kernel for ReplId-4eca4-c68d0-068a5-6, kernel exited with exit code 1.
----- stdout -----

------------------
----- stderr -----
Traceback (most recent call last):
  File &quot;/databricks/python_shell/scripts/db_ipykernel_launcher.py&quot;, line 43, in &lt;module&gt;
    from dbruntime import UserNamespaceInitializer
  File &quot;/databricks/python_shell/dbruntime/UserNamespaceInitializer.py&quot;, line 2, in &lt;module&gt;
    from dbruntime.display import Display, displayHTML
  File &quot;/databricks/python_shell/dbruntime/display.py&quot;, line 3, in &lt;module&gt;
    from pyspark.sql.connect.dataframe import DataFrame as ConnectDataFrame
  File &quot;/databricks/spark/python/pyspark/sql/connect/dataframe.py&quot;, line 65, in &lt;module&gt;
    import pyspark.sql.connect.plan as plan
  File &quot;/databricks/spark/python/pyspark/sql/connect/plan.py&quot;, line 32, in &lt;module&gt;
    import pyspark.sql.connect.proto as proto
  File &quot;/databricks/spark/python/pyspark/sql/connect/proto/__init__.py&quot;, line 18, in &lt;module&gt;
    from pyspark.sql.connect.proto.base_pb2_grpc import *
  File &quot;/databricks/spark/python/pyspark/sql/connect/proto/base_pb2_grpc.py&quot;, line 21, in &lt;module&gt;
    from pyspark.sql.connect.proto import base_pb2 as spark_dot_connect_dot_base__pb2
  File &quot;/databricks/spark/python/pyspark/sql/connect/proto/base_pb2.py&quot;, line 21, in &lt;module&gt;
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

------------------

	at com.databricks.backend.daemon.driver.IpykernelUtils$.startReplFailure$1(JupyterDriverLocal.scala:1179)
	at com.databricks.backend.daemon.driver.IpykernelUtils$.$anonfun$startIpyKernel$3(JupyterDriverLocal.scala:1189)
	at com.databricks.backend.common.util.TimeUtils$.$anonfun$retryWithExponentialBackoff0$1(TimeUtils.scala:191)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.common.util.TimeUtils$.retryWithExponentialBackoff0(TimeUtils.scala:191)
	at com.databricks.backend.common.util.TimeUtils$.retryWithExponentialBackoff(TimeUtils.scala:145)
	at com.databricks.backend.common.util.TimeUtils$.retryWithTimeout(TimeUtils.scala:94)
	at com.databricks.backend.daemon.driver.IpykernelUtils$.startIpyKernel(JupyterDriverLocal.scala:1187)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.$anonfun$startPython$1(JupyterDriverLocal.scala:908)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.com$databricks$backend$daemon$driver$JupyterDriverLocal$$withRetry(JupyterDriverLocal.scala:872)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal$$anonfun$com$databricks$backend$daemon$driver$JupyterDriverLocal$$withRetry$1.applyOrElse(JupyterDriverLocal.scala:875)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal$$anonfun$com$databricks$backend$daemon$driver$JupyterDriverLocal$$withRetry$1.applyOrElse(JupyterDriverLocal.scala:872)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recover(Try.scala:234)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.com$databricks$backend$daemon$driver$JupyterDriverLocal$$withRetry(JupyterDriverLocal.scala:872)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.startPython(JupyterDriverLocal.scala:889)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.&lt;init&gt;(JupyterDriverLocal.scala:371)
	at com.databricks.backend.daemon.driver.PythonDriverWrapper.instantiateDriver(DriverWrapper.scala:829)
	at com.databricks.backend.daemon.driver.DriverWrapper.setupRepl(DriverWrapper.scala:369)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:258)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by mattmazzola** [comment]
I saw this other issue https://github.com/databricks/containers/issues/116#issuecomment-1665762751 suggesting downgrading the runtime to 12.x might help.
I tried 12.2 but still see the same error

**Comment by marcindulak** [comment]
Is the problem you noticed similar to https://github.com/databricks/containers/issues/150?

**Comment by xinzhao-db** [comment]
@mattmazzola is this still an issue? I cannot reproduce with 13.3-LTS image
